# -*- coding: utf-8 -*-
"""customer churn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xP0ef5XUOP_AKOeWobWD4P0ettzZYT_y
"""

!pip install faker

import pandas as pd
import numpy as np
from faker import Faker
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

fake = Faker()

data = []

for i in range(100000):
    age = random.randint(18, 70)
    tenure = random.randint(0, 10)
    balance = round(random.uniform(0, 200000), 2)
    credit_score = random.randint(300, 900)
    salary = round(random.uniform(10000, 150000), 2)
    products = random.randint(1, 4)
    active = random.choice([0, 1])
    churn = 0
    if (balance < 50000 and active == 0) or (credit_score < 500 and products == 1):
        churn = 1

    data.append([
        i, age, random.choice(['Male', 'Female']), tenure,
        balance, credit_score, salary, products, active, churn
    ])

columns = [
    'Customer_ID', 'Age', 'Gender', 'Tenure', 'Balance',
    'CreditScore', 'EstimatedSalary', 'NumOfProducts',
    'IsActiveMember', 'Churn'
]

df = pd.DataFrame(data, columns=columns)

df.head()

print(df.info())
print(df.isnull().sum())
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

sns.countplot(x='Churn', data=df)
plt.title("Churn Distribution")
plt.show()

sns.boxplot(x='Churn', y='Age', data=df)
plt.show()

sns.boxplot(x='Churn', y='Balance', data=df)
plt.show()

X = df.drop(['Customer_ID', 'Churn'], axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

importances = model.feature_importances_
features = X.columns

sns.barplot(x=importances, y=features)
plt.title("Feature Importance")
plt.show()